package ru.ovcharov_alexey.tanks.v4.ui.forms;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractListModel;
import ru.ovcharov_alexey.tanks.v4.engine.Global;

/**
 *
 * @author Admin
 */
public class AcheivementsForm extends javax.swing.JDialog {

    /**
     * Creates new form AchievementsForm
     *
     * @param parent
     * @param modal
     */
    public AcheivementsForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationCenter();
        initModel();
    }

    private void initModel() {
        Map<String, String> achievements = Global.getAchievements();
        List<String> names = new ArrayList<>(achievements.keySet());
        listAchievements.setModel(new AbstractListModel<String>() {
            @Override
            public String getElementAt(int index) {
                return names.get(index);
            }

            @Override
            public int getSize() {
                return names.size();
            }
        });
    }

    private void setDescription() {
        String selectedValue = listAchievements.getSelectedValue();
        if (selectedValue != null) {
            String acheivementByName = Global.getAcheivementByName(selectedValue);
            if (acheivementByName != null) {
                lDescription.setText("<html>" + acheivementByName);
            }
        }
    }

    private void setLocationCenter() {
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listAchievements = new javax.swing.JList<>();
        lDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Достижения");

        listAchievements.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listAchievements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listAchievementsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listAchievements);

        lDescription.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAchievementsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAchievementsMousePressed
        setDescription();
    }//GEN-LAST:event_listAchievementsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDescription;
    private javax.swing.JList<String> listAchievements;
    // End of variables declaration//GEN-END:variables
}
